name: CI

on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        sdk: [macosx, iphoneos]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bundle
      run: bundle install
    - name: Generate Xcode project
      run: bundle exec fastlane run spm command:generate-xcodeproj
    - name: Build target
      run: bundle exec fastlane run gym sdk:${{ matrix.sdk }}
